name: Another

on: [push]

jobs:
  build-number-two:
    needs: build-number-one
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo This is a second Workflow
